//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Magro.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Magro.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   @echo off
        ///go mod tidy
        ///go build .
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string build_bat {
            get {
                return ResourceManager.GetString("build_bat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   module magro
        ///
        ///go 1.23.4
        ///
        ///require github.com/hajimehoshi/ebiten/v2 v2.8.6
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string go_mod {
            get {
                return ResourceManager.GetString("go_mod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   package main
        ///
        ///import (
        ///	&quot;log&quot;
        ///
        ///	&quot;github.com/hajimehoshi/ebiten/v2&quot;
        ///	&quot;github.com/hajimehoshi/ebiten/v2/ebitenutil&quot;
        ///)
        ///
        ///type Game struct{}
        ///
        ///func (g *Game) Update() error {
        ///	return nil
        ///}
        ///
        ///func (g *Game) Draw(screen *ebiten.Image) {
        ///	ebitenutil.DebugPrint(screen, &quot;Magro world&quot;)
        ///}
        ///
        ///func (g *Game) Layout(outsideWidth, outsideHeight int) (screenWidth, screenHeight int) {
        ///	return 320, 240
        ///}
        ///
        ///func main() {
        ///	ebiten.SetWindowSize(640, 480)
        ///	ebiten.SetWindowTitle(&quot;magro/runtime&quot;)
        ///	if err := ebi [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string main_go {
            get {
                return ResourceManager.GetString("main_go", resourceCulture);
            }
        }
    }
}
